apiVersion: v1
kind: Secret
metadata:
  name: inventory-secrets
  namespace: inventory-service
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  SECRET_KEY: "change-this-to-secure-random-key-in-production"